spring:
  main:
    allow-circular-references: true
  # 접속 DB 설정
  datasource:
    url: "jdbc:mysql://13.124.114.13:3306/aword"
    username: "root"
    password: "zinna123"
    driver-class-name: "org.mariadb.jdbc.Driver"
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  webflux:
    static-path-pattern: /resources/**
  mail:
    host: smtp.gmail.com
    port: 465
    username: zvs@zinnaworks.com 
    password: zinna432!
    properties:
     mail:
     smtp:
     auth: true
     starttls:
     enable: true
     required: true
     soketFactory:
     fallback: false
     port: 465
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  servlet:
    session:
      timeout: 10m
      tracking-modes: cookie
            
mybatis:
  # mapper 경로 지정
  mapper-locations: mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
